server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  types {
    text/html html;
    text/css css;
    application/javascript js;
  }

  gzip on;
  gzip_types text/css application/javascript text/html;
}