sonar.projectKey=Frontend-Angular
sonar.projectName=Frontend Angular
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=src

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=node_modules/**,dist/**,.angular/**,coverage/**,.scannerwork/**

sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info

sonar.host.url=http://localhost:9000
sonar.login=sqp_4248d7b97a7bf1da3ff74199f04a4c8542d0694c